/*
 * IXOPAY Payment Platform
 * IXOPAY Payment Platform
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@ixopay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ixopay.core.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * ChargebackData
 */
@JsonPropertyOrder({
  ChargebackData.JSON_PROPERTY_ORIGINAL_UUID,
  ChargebackData.JSON_PROPERTY_ORIGINAL_MERCHANT_TRANSACTION_ID,
  ChargebackData.JSON_PROPERTY_AMOUNT,
  ChargebackData.JSON_PROPERTY_CURRENCY,
  ChargebackData.JSON_PROPERTY_REASON,
  ChargebackData.JSON_PROPERTY_CHARGEBACK_DATE_TIME
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ChargebackData {
  public static final String JSON_PROPERTY_ORIGINAL_UUID = "originalUuid";
  private String originalUuid;

  public static final String JSON_PROPERTY_ORIGINAL_MERCHANT_TRANSACTION_ID = "originalMerchantTransactionId";
  private String originalMerchantTransactionId;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private String amount;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  private String currency;

  public static final String JSON_PROPERTY_REASON = "reason";
  private String reason;

  public static final String JSON_PROPERTY_CHARGEBACK_DATE_TIME = "chargebackDateTime";
  private OffsetDateTime chargebackDateTime;

  public ChargebackData() { 
  }

  public ChargebackData originalUuid(String originalUuid) {
    this.originalUuid = originalUuid;
    return this;
  }

   /**
   * Get originalUuid
   * @return originalUuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORIGINAL_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOriginalUuid() {
    return originalUuid;
  }


  @JsonProperty(JSON_PROPERTY_ORIGINAL_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOriginalUuid(String originalUuid) {
    this.originalUuid = originalUuid;
  }


  public ChargebackData originalMerchantTransactionId(String originalMerchantTransactionId) {
    this.originalMerchantTransactionId = originalMerchantTransactionId;
    return this;
  }

   /**
   * Get originalMerchantTransactionId
   * @return originalMerchantTransactionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORIGINAL_MERCHANT_TRANSACTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOriginalMerchantTransactionId() {
    return originalMerchantTransactionId;
  }


  @JsonProperty(JSON_PROPERTY_ORIGINAL_MERCHANT_TRANSACTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOriginalMerchantTransactionId(String originalMerchantTransactionId) {
    this.originalMerchantTransactionId = originalMerchantTransactionId;
  }


  public ChargebackData amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmount(String amount) {
    this.amount = amount;
  }


  public ChargebackData currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrency() {
    return currency;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public ChargebackData reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReason() {
    return reason;
  }


  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReason(String reason) {
    this.reason = reason;
  }


  public ChargebackData chargebackDateTime(OffsetDateTime chargebackDateTime) {
    this.chargebackDateTime = chargebackDateTime;
    return this;
  }

   /**
   * Get chargebackDateTime
   * @return chargebackDateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHARGEBACK_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getChargebackDateTime() {
    return chargebackDateTime;
  }


  @JsonProperty(JSON_PROPERTY_CHARGEBACK_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChargebackDateTime(OffsetDateTime chargebackDateTime) {
    this.chargebackDateTime = chargebackDateTime;
  }


  /**
   * Return true if this ChargebackData object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChargebackData chargebackData = (ChargebackData) o;
    return Objects.equals(this.originalUuid, chargebackData.originalUuid) &&
        Objects.equals(this.originalMerchantTransactionId, chargebackData.originalMerchantTransactionId) &&
        Objects.equals(this.amount, chargebackData.amount) &&
        Objects.equals(this.currency, chargebackData.currency) &&
        Objects.equals(this.reason, chargebackData.reason) &&
        Objects.equals(this.chargebackDateTime, chargebackData.chargebackDateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(originalUuid, originalMerchantTransactionId, amount, currency, reason, chargebackDateTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChargebackData {\n");
    sb.append("    originalUuid: ").append(toIndentedString(originalUuid)).append("\n");
    sb.append("    originalMerchantTransactionId: ").append(toIndentedString(originalMerchantTransactionId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    chargebackDateTime: ").append(toIndentedString(chargebackDateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

