/*
 * IXOPAY Payment Platform
 * IXOPAY Payment Platform
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@ixopay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ixopay.core.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * PaymentWalletDataWalletData
 */
@JsonPropertyOrder({
  PaymentWalletDataWalletData.JSON_PROPERTY_WALLET_REFERENCE_ID,
  PaymentWalletDataWalletData.JSON_PROPERTY_WALLET_OWNER,
  PaymentWalletDataWalletData.JSON_PROPERTY_WALLET_TYPE
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PaymentWalletDataWalletData {
  public static final String JSON_PROPERTY_WALLET_REFERENCE_ID = "walletReferenceId";
  private String walletReferenceId;

  public static final String JSON_PROPERTY_WALLET_OWNER = "walletOwner";
  private String walletOwner;

  public static final String JSON_PROPERTY_WALLET_TYPE = "walletType";
  private String walletType;

  public PaymentWalletDataWalletData() { 
  }

  public PaymentWalletDataWalletData walletReferenceId(String walletReferenceId) {
    this.walletReferenceId = walletReferenceId;
    return this;
  }

   /**
   * Get walletReferenceId
   * @return walletReferenceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WALLET_REFERENCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWalletReferenceId() {
    return walletReferenceId;
  }


  @JsonProperty(JSON_PROPERTY_WALLET_REFERENCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWalletReferenceId(String walletReferenceId) {
    this.walletReferenceId = walletReferenceId;
  }


  public PaymentWalletDataWalletData walletOwner(String walletOwner) {
    this.walletOwner = walletOwner;
    return this;
  }

   /**
   * Get walletOwner
   * @return walletOwner
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WALLET_OWNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWalletOwner() {
    return walletOwner;
  }


  @JsonProperty(JSON_PROPERTY_WALLET_OWNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWalletOwner(String walletOwner) {
    this.walletOwner = walletOwner;
  }


  public PaymentWalletDataWalletData walletType(String walletType) {
    this.walletType = walletType;
    return this;
  }

   /**
   * Get walletType
   * @return walletType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WALLET_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWalletType() {
    return walletType;
  }


  @JsonProperty(JSON_PROPERTY_WALLET_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWalletType(String walletType) {
    this.walletType = walletType;
  }


  /**
   * Return true if this PaymentWalletData_walletData object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentWalletDataWalletData paymentWalletDataWalletData = (PaymentWalletDataWalletData) o;
    return Objects.equals(this.walletReferenceId, paymentWalletDataWalletData.walletReferenceId) &&
        Objects.equals(this.walletOwner, paymentWalletDataWalletData.walletOwner) &&
        Objects.equals(this.walletType, paymentWalletDataWalletData.walletType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(walletReferenceId, walletOwner, walletType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentWalletDataWalletData {\n");
    sb.append("    walletReferenceId: ").append(toIndentedString(walletReferenceId)).append("\n");
    sb.append("    walletOwner: ").append(toIndentedString(walletOwner)).append("\n");
    sb.append("    walletType: ").append(toIndentedString(walletType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

