/*
 * IXOPAY Payment Platform
 * IXOPAY Payment Platform
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@ixopay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ixopay.core.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ixopay.core.model.PaymentIbanDataIbanData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * PaymentIbanData
 */
@JsonPropertyOrder({
  PaymentIbanData.JSON_PROPERTY_IBAN_DATA
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PaymentIbanData {
  public static final String JSON_PROPERTY_IBAN_DATA = "ibanData";
  private PaymentIbanDataIbanData ibanData;

  public PaymentIbanData() { 
  }

  public PaymentIbanData ibanData(PaymentIbanDataIbanData ibanData) {
    this.ibanData = ibanData;
    return this;
  }

   /**
   * Get ibanData
   * @return ibanData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IBAN_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PaymentIbanDataIbanData getIbanData() {
    return ibanData;
  }


  @JsonProperty(JSON_PROPERTY_IBAN_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIbanData(PaymentIbanDataIbanData ibanData) {
    this.ibanData = ibanData;
  }


  /**
   * Return true if this PaymentIbanData object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentIbanData paymentIbanData = (PaymentIbanData) o;
    return Objects.equals(this.ibanData, paymentIbanData.ibanData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ibanData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentIbanData {\n");
    sb.append("    ibanData: ").append(toIndentedString(ibanData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

