/*
 * IXOPAY Payment Platform
 * IXOPAY Payment Platform
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@ixopay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ixopay.core.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ixopay.core.model.CardData;
import com.ixopay.core.model.IbanData;
import com.ixopay.core.model.PhoneData;
import com.ixopay.core.model.ReturnData;
import com.ixopay.core.model.ReturnDataType;
import com.ixopay.core.model.WalletData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.ixopay.core.client.JSON;
/**
 * WalletData
 */
@JsonPropertyOrder({
  WalletData.JSON_PROPERTY_WALLET_REFERENCE_ID,
  WalletData.JSON_PROPERTY_WALLET_OWNER,
  WalletData.JSON_PROPERTY_WALLET_TYPE
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
@JsonIgnoreProperties(
  value = "_TYPE", // ignore manually set _TYPE, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the _TYPE to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_TYPE", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = CardData.class, name = "cardData"),
  @JsonSubTypes.Type(value = IbanData.class, name = "ibanData"),
  @JsonSubTypes.Type(value = PhoneData.class, name = "phoneData"),
  @JsonSubTypes.Type(value = WalletData.class, name = "walletData"),
})

public class WalletData extends ReturnData {
  public static final String JSON_PROPERTY_WALLET_REFERENCE_ID = "walletReferenceId";
  private String walletReferenceId;

  public static final String JSON_PROPERTY_WALLET_OWNER = "walletOwner";
  private String walletOwner;

  public static final String JSON_PROPERTY_WALLET_TYPE = "walletType";
  private String walletType;

  public WalletData() { 
  }

  public WalletData walletReferenceId(String walletReferenceId) {
    this.walletReferenceId = walletReferenceId;
    return this;
  }

   /**
   * Get walletReferenceId
   * @return walletReferenceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WALLET_REFERENCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWalletReferenceId() {
    return walletReferenceId;
  }


  @JsonProperty(JSON_PROPERTY_WALLET_REFERENCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWalletReferenceId(String walletReferenceId) {
    this.walletReferenceId = walletReferenceId;
  }


  public WalletData walletOwner(String walletOwner) {
    this.walletOwner = walletOwner;
    return this;
  }

   /**
   * Get walletOwner
   * @return walletOwner
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WALLET_OWNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWalletOwner() {
    return walletOwner;
  }


  @JsonProperty(JSON_PROPERTY_WALLET_OWNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWalletOwner(String walletOwner) {
    this.walletOwner = walletOwner;
  }


  public WalletData walletType(String walletType) {
    this.walletType = walletType;
    return this;
  }

   /**
   * Get walletType
   * @return walletType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WALLET_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWalletType() {
    return walletType;
  }


  @JsonProperty(JSON_PROPERTY_WALLET_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWalletType(String walletType) {
    this.walletType = walletType;
  }


  /**
   * Return true if this walletData object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WalletData walletData = (WalletData) o;
    return Objects.equals(this.walletReferenceId, walletData.walletReferenceId) &&
        Objects.equals(this.walletOwner, walletData.walletOwner) &&
        Objects.equals(this.walletType, walletData.walletType) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(walletReferenceId, walletOwner, walletType, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WalletData {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    walletReferenceId: ").append(toIndentedString(walletReferenceId)).append("\n");
    sb.append("    walletOwner: ").append(toIndentedString(walletOwner)).append("\n");
    sb.append("    walletType: ").append(toIndentedString(walletType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("cardData", CardData.class);
  mappings.put("ibanData", IbanData.class);
  mappings.put("phoneData", PhoneData.class);
  mappings.put("walletData", WalletData.class);
  mappings.put("walletData", WalletData.class);
  JSON.registerDiscriminator(WalletData.class, "_TYPE", mappings);
}
}

