//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.28 at 02:15:42 PM CEST 
//


package com.ixopay.client.model.callback;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for returnDataTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="returnDataTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="creditcardData"/>
 *     &lt;enumeration value="phoneData"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "returnDataTypeEnum")
@XmlEnum
public enum ReturnDataTypeEnum {

    @XmlEnumValue("creditcardData")
    CREDITCARD_DATA("creditcardData"),
    @XmlEnumValue("phoneData")
    PHONE_DATA("phoneData");
    private final String value;

    ReturnDataTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReturnDataTypeEnum fromValue(String v) {
        for (ReturnDataTypeEnum c: ReturnDataTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
