/*
 * IXOPAY Payment Platform
 * IXOPAY Payment Platform
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@ixopay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ixopay.client.core.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * PayByLink
 */
@JsonPropertyOrder({
  PayByLink.JSON_PROPERTY_SEND_BY_EMAIL,
  PayByLink.JSON_PROPERTY_EXPIRATION_IN_MINUTE
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegenWithComposedSchema")
public class PayByLink {
  public static final String JSON_PROPERTY_SEND_BY_EMAIL = "sendByEmail";
  private Boolean sendByEmail;

  public static final String JSON_PROPERTY_EXPIRATION_IN_MINUTE = "expirationInMinute";
  private Integer expirationInMinute;

  public PayByLink() { 
  }

  public PayByLink sendByEmail(Boolean sendByEmail) {
    this.sendByEmail = sendByEmail;
    return this;
  }

   /**
   * Get sendByEmail
   * @return sendByEmail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SEND_BY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSendByEmail() {
    return sendByEmail;
  }


  @JsonProperty(JSON_PROPERTY_SEND_BY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSendByEmail(Boolean sendByEmail) {
    this.sendByEmail = sendByEmail;
  }


  public PayByLink expirationInMinute(Integer expirationInMinute) {
    this.expirationInMinute = expirationInMinute;
    return this;
  }

   /**
   * Get expirationInMinute
   * minimum: 1
   * @return expirationInMinute
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXPIRATION_IN_MINUTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getExpirationInMinute() {
    return expirationInMinute;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRATION_IN_MINUTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpirationInMinute(Integer expirationInMinute) {
    this.expirationInMinute = expirationInMinute;
  }


  /**
   * Return true if this PayByLink object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayByLink payByLink = (PayByLink) o;
    return Objects.equals(this.sendByEmail, payByLink.sendByEmail) &&
        Objects.equals(this.expirationInMinute, payByLink.expirationInMinute);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sendByEmail, expirationInMinute);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayByLink {\n");
    sb.append("    sendByEmail: ").append(toIndentedString(sendByEmail)).append("\n");
    sb.append("    expirationInMinute: ").append(toIndentedString(expirationInMinute)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

