/*
 * IXOPAY Payment Platform
 * IXOPAY Payment Platform
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@ixopay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ixopay.client.core.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets TransactionType
 */
public enum TransactionType {
  
  DEBIT("DEBIT"),
  
  CAPTURE("CAPTURE"),
  
  DEREGISTER("DEREGISTER"),
  
  PREAUTHORIZE("PREAUTHORIZE"),
  
  REFUND("REFUND"),
  
  REGISTER("REGISTER"),
  
  VOID("VOID"),
  
  CHARGEBACK("CHARGEBACK"),
  
  CHARGEBACK_REVERSAL("CHARGEBACK-REVERSAL"),
  
  PAYOUT("PAYOUT"),
  
  INCREMENTAL_AUTHORIZATION("INCREMENTAL-AUTHORIZATION"),
  
  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  TransactionType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TransactionType fromValue(String value) {
    for (TransactionType b : TransactionType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }
}

