/*
 * IXOPAY Payment Platform
 * IXOPAY Payment Platform
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@ixopay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ixopay.client.core.api;

import com.ixopay.client.signing.HttpHeaders;
import com.ixopay.client.signing.ApiRequestAuthenticator;
import com.ixopay.client.signing.ApiRequestSigner;
import com.ixopay.client.signing.model.ApiRequestHeadersAuthentication;
import com.ixopay.client.signing.model.ApiRequestHeadersSignature;
import com.ixopay.client.signing.model.ApiUser;
import com.ixopay.client.signing.model.HttpRequestInfo;
import com.ixopay.client.core.client.ApiClient;
import com.ixopay.client.core.client.ApiException;
import com.ixopay.client.core.client.ApiResponse;
import com.ixopay.client.core.client.Pair;

import com.ixopay.client.core.model.CancelSchedule;
import com.ixopay.client.core.model.ContinueSchedule;
import com.ixopay.client.core.model.MaybeScheduleResponse;
import com.ixopay.client.core.model.PauseSchedule;
import com.ixopay.client.core.model.StartSchedule;
import com.ixopay.client.core.model.UpdateSchedule;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

import javax.annotation.Nullable;

@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegenWithComposedSchema")
public class ScheduleApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final ApiUser memberVarApiUser;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public ScheduleApi(ApiUser apiUser) {
    this(new ApiClient(apiUser));
  }

  public ScheduleApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarApiUser = apiClient.getApiUser();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Cancel a schedule. Requires the registrationId of an existing transaction of type Register / Debit-with-register / Preuathorize-with-register
   * 
   * @param apiKey API Key of Connector (required)
   * @param scheduleId ID of the schedule (required)
   * @param cancelSchedule Cancel a schedule (required)
   * @return MaybeScheduleResponse
   * @throws ApiException if fails to make API call
   */
  public MaybeScheduleResponse cancelSchedule(String apiKey, String scheduleId, CancelSchedule cancelSchedule) throws ApiException {
    return  cancelSchedule(null, apiKey, scheduleId, cancelSchedule);
  }

  /**
   * Cancel a schedule. Requires the registrationId of an existing transaction of type Register / Debit-with-register / Preuathorize-with-register
   * 
   * @param sharedSecret optional shared secret for signing requests (can be {@code null}).
   * @param apiKey API Key of Connector (required)
   * @param scheduleId ID of the schedule (required)
   * @param cancelSchedule Cancel a schedule (required)
   * @return MaybeScheduleResponse
   * @throws ApiException if fails to make API call
   */
  public MaybeScheduleResponse cancelSchedule(@Nullable String sharedSecret, String apiKey, String scheduleId, CancelSchedule cancelSchedule) throws ApiException {
    ApiResponse<MaybeScheduleResponse> localVarResponse = cancelScheduleWithHttpInfo(sharedSecret, apiKey, scheduleId, cancelSchedule);
    return localVarResponse.getData();
  }

  /**
   * Cancel a schedule. Requires the registrationId of an existing transaction of type Register / Debit-with-register / Preuathorize-with-register
   * 
   * @param apiKey API Key of Connector (required)
   * @param scheduleId ID of the schedule (required)
   * @param cancelSchedule Cancel a schedule (required)
   * @return ApiResponse&lt;MaybeScheduleResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MaybeScheduleResponse> cancelScheduleWithHttpInfo(String apiKey, String scheduleId, CancelSchedule cancelSchedule) throws ApiException {
    return cancelScheduleWithHttpInfo(null, apiKey, scheduleId, cancelSchedule);
  }

  /**
   * Cancel a schedule. Requires the registrationId of an existing transaction of type Register / Debit-with-register / Preuathorize-with-register
   * 
   * @param sharedSecret optional shared secret for signing requests (can be {@code null}).
   * @param apiKey API Key of Connector (required)
   * @param scheduleId ID of the schedule (required)
   * @param cancelSchedule Cancel a schedule (required)
   * @return ApiResponse&lt;MaybeScheduleResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MaybeScheduleResponse> cancelScheduleWithHttpInfo(@Nullable String sharedSecret, String apiKey, String scheduleId, CancelSchedule cancelSchedule) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = cancelScheduleRequestBuilder(sharedSecret, apiKey, scheduleId, cancelSchedule);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        return new ApiResponse<MaybeScheduleResponse>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<MaybeScheduleResponse>() {}) // closes the InputStream
          
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder cancelScheduleRequestBuilder(@Nullable String sharedSecret, String apiKey, String scheduleId, CancelSchedule cancelSchedule) throws ApiException {
    // verify the required parameter 'apiKey' is set
    if (apiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'apiKey' when calling cancelSchedule");
    }
    // verify the required parameter 'scheduleId' is set
    if (scheduleId == null) {
      throw new ApiException(400, "Missing the required parameter 'scheduleId' when calling cancelSchedule");
    }
    // verify the required parameter 'cancelSchedule' is set
    if (cancelSchedule == null) {
      throw new ApiException(400, "Missing the required parameter 'cancelSchedule' when calling cancelSchedule");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/schedule/{apiKey}/{scheduleId}/cancel"
        .replace("{apiKey}", ApiClient.urlEncode(apiKey.toString()))
        .replace("{scheduleId}", ApiClient.urlEncode(scheduleId.toString()));

    ApiRequestHeadersAuthentication authentication = ApiRequestAuthenticator.authenticate(memberVarApiUser);
    localVarRequestBuilder.header(HttpHeaders.authorization(), authentication.getAuthorizationHeader());

    URI localVarUri = URI.create(memberVarBaseUri + localVarPath);
    localVarRequestBuilder.uri(localVarUri);

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");
    localVarRequestBuilder.header("User-Agent", "ixopay-java-sdk 3.0.0");

    byte[] localVarSignatureBody;
    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(cancelSchedule);
      localVarSignatureBody = localVarPostBody;
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }

    HttpRequestInfo localVarRequestInfo = ApiRequestSigner.requestInfo()
      .withUri(localVarUri)
      .withMethod("POST")
      .withContentTypeHeader("application/json")
      .withBody(localVarSignatureBody)
      .build();
    localVarRequestBuilder.header(HttpHeaders.date(), localVarRequestInfo.getNow());
    if(sharedSecret != null && localVarSignatureBody != null) {
      ApiRequestHeadersSignature signature = ApiRequestSigner.sign(sharedSecret, localVarRequestInfo);

      localVarRequestBuilder.header(HttpHeaders.xSignature(), signature.getXSignatureHeader());
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Continue a schedule which has been paused. Requires the registrationId of an existing transaction of type Register / Debit-with-register / Preuathorize-with-register
   * 
   * @param apiKey API Key of Connector (required)
   * @param scheduleId ID of the schedule (required)
   * @param continueSchedule Continue a given schedule on given date and time (required)
   * @return MaybeScheduleResponse
   * @throws ApiException if fails to make API call
   */
  public MaybeScheduleResponse continueSchedule(String apiKey, String scheduleId, ContinueSchedule continueSchedule) throws ApiException {
    return  continueSchedule(null, apiKey, scheduleId, continueSchedule);
  }

  /**
   * Continue a schedule which has been paused. Requires the registrationId of an existing transaction of type Register / Debit-with-register / Preuathorize-with-register
   * 
   * @param sharedSecret optional shared secret for signing requests (can be {@code null}).
   * @param apiKey API Key of Connector (required)
   * @param scheduleId ID of the schedule (required)
   * @param continueSchedule Continue a given schedule on given date and time (required)
   * @return MaybeScheduleResponse
   * @throws ApiException if fails to make API call
   */
  public MaybeScheduleResponse continueSchedule(@Nullable String sharedSecret, String apiKey, String scheduleId, ContinueSchedule continueSchedule) throws ApiException {
    ApiResponse<MaybeScheduleResponse> localVarResponse = continueScheduleWithHttpInfo(sharedSecret, apiKey, scheduleId, continueSchedule);
    return localVarResponse.getData();
  }

  /**
   * Continue a schedule which has been paused. Requires the registrationId of an existing transaction of type Register / Debit-with-register / Preuathorize-with-register
   * 
   * @param apiKey API Key of Connector (required)
   * @param scheduleId ID of the schedule (required)
   * @param continueSchedule Continue a given schedule on given date and time (required)
   * @return ApiResponse&lt;MaybeScheduleResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MaybeScheduleResponse> continueScheduleWithHttpInfo(String apiKey, String scheduleId, ContinueSchedule continueSchedule) throws ApiException {
    return continueScheduleWithHttpInfo(null, apiKey, scheduleId, continueSchedule);
  }

  /**
   * Continue a schedule which has been paused. Requires the registrationId of an existing transaction of type Register / Debit-with-register / Preuathorize-with-register
   * 
   * @param sharedSecret optional shared secret for signing requests (can be {@code null}).
   * @param apiKey API Key of Connector (required)
   * @param scheduleId ID of the schedule (required)
   * @param continueSchedule Continue a given schedule on given date and time (required)
   * @return ApiResponse&lt;MaybeScheduleResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MaybeScheduleResponse> continueScheduleWithHttpInfo(@Nullable String sharedSecret, String apiKey, String scheduleId, ContinueSchedule continueSchedule) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = continueScheduleRequestBuilder(sharedSecret, apiKey, scheduleId, continueSchedule);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        return new ApiResponse<MaybeScheduleResponse>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<MaybeScheduleResponse>() {}) // closes the InputStream
          
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder continueScheduleRequestBuilder(@Nullable String sharedSecret, String apiKey, String scheduleId, ContinueSchedule continueSchedule) throws ApiException {
    // verify the required parameter 'apiKey' is set
    if (apiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'apiKey' when calling continueSchedule");
    }
    // verify the required parameter 'scheduleId' is set
    if (scheduleId == null) {
      throw new ApiException(400, "Missing the required parameter 'scheduleId' when calling continueSchedule");
    }
    // verify the required parameter 'continueSchedule' is set
    if (continueSchedule == null) {
      throw new ApiException(400, "Missing the required parameter 'continueSchedule' when calling continueSchedule");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/schedule/{apiKey}/{scheduleId}/continue"
        .replace("{apiKey}", ApiClient.urlEncode(apiKey.toString()))
        .replace("{scheduleId}", ApiClient.urlEncode(scheduleId.toString()));

    ApiRequestHeadersAuthentication authentication = ApiRequestAuthenticator.authenticate(memberVarApiUser);
    localVarRequestBuilder.header(HttpHeaders.authorization(), authentication.getAuthorizationHeader());

    URI localVarUri = URI.create(memberVarBaseUri + localVarPath);
    localVarRequestBuilder.uri(localVarUri);

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");
    localVarRequestBuilder.header("User-Agent", "ixopay-java-sdk 3.0.0");

    byte[] localVarSignatureBody;
    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(continueSchedule);
      localVarSignatureBody = localVarPostBody;
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }

    HttpRequestInfo localVarRequestInfo = ApiRequestSigner.requestInfo()
      .withUri(localVarUri)
      .withMethod("POST")
      .withContentTypeHeader("application/json")
      .withBody(localVarSignatureBody)
      .build();
    localVarRequestBuilder.header(HttpHeaders.date(), localVarRequestInfo.getNow());
    if(sharedSecret != null && localVarSignatureBody != null) {
      ApiRequestHeadersSignature signature = ApiRequestSigner.sign(sharedSecret, localVarRequestInfo);

      localVarRequestBuilder.header(HttpHeaders.xSignature(), signature.getXSignatureHeader());
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Retrieve a schedule. Requires the UUID of an existing transaction of type Register / Debit-with-register / Preuathorize-with-register
   * 
   * @param apiKey API Key of Connector (required)
   * @param scheduleId ID of the schedule (required)
   * @return MaybeScheduleResponse
   * @throws ApiException if fails to make API call
   */
  public MaybeScheduleResponse getSchedule(String apiKey, String scheduleId) throws ApiException {
    return  getSchedule(null, apiKey, scheduleId);
  }

  /**
   * Retrieve a schedule. Requires the UUID of an existing transaction of type Register / Debit-with-register / Preuathorize-with-register
   * 
   * @param sharedSecret optional shared secret for signing requests (can be {@code null}).
   * @param apiKey API Key of Connector (required)
   * @param scheduleId ID of the schedule (required)
   * @return MaybeScheduleResponse
   * @throws ApiException if fails to make API call
   */
  public MaybeScheduleResponse getSchedule(@Nullable String sharedSecret, String apiKey, String scheduleId) throws ApiException {
    ApiResponse<MaybeScheduleResponse> localVarResponse = getScheduleWithHttpInfo(sharedSecret, apiKey, scheduleId);
    return localVarResponse.getData();
  }

  /**
   * Retrieve a schedule. Requires the UUID of an existing transaction of type Register / Debit-with-register / Preuathorize-with-register
   * 
   * @param apiKey API Key of Connector (required)
   * @param scheduleId ID of the schedule (required)
   * @return ApiResponse&lt;MaybeScheduleResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MaybeScheduleResponse> getScheduleWithHttpInfo(String apiKey, String scheduleId) throws ApiException {
    return getScheduleWithHttpInfo(null, apiKey, scheduleId);
  }

  /**
   * Retrieve a schedule. Requires the UUID of an existing transaction of type Register / Debit-with-register / Preuathorize-with-register
   * 
   * @param sharedSecret optional shared secret for signing requests (can be {@code null}).
   * @param apiKey API Key of Connector (required)
   * @param scheduleId ID of the schedule (required)
   * @return ApiResponse&lt;MaybeScheduleResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MaybeScheduleResponse> getScheduleWithHttpInfo(@Nullable String sharedSecret, String apiKey, String scheduleId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getScheduleRequestBuilder(sharedSecret, apiKey, scheduleId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        return new ApiResponse<MaybeScheduleResponse>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<MaybeScheduleResponse>() {}) // closes the InputStream
          
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getScheduleRequestBuilder(@Nullable String sharedSecret, String apiKey, String scheduleId) throws ApiException {
    // verify the required parameter 'apiKey' is set
    if (apiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'apiKey' when calling getSchedule");
    }
    // verify the required parameter 'scheduleId' is set
    if (scheduleId == null) {
      throw new ApiException(400, "Missing the required parameter 'scheduleId' when calling getSchedule");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/schedule/{apiKey}/{scheduleId}/get"
        .replace("{apiKey}", ApiClient.urlEncode(apiKey.toString()))
        .replace("{scheduleId}", ApiClient.urlEncode(scheduleId.toString()));

    ApiRequestHeadersAuthentication authentication = ApiRequestAuthenticator.authenticate(memberVarApiUser);
    localVarRequestBuilder.header(HttpHeaders.authorization(), authentication.getAuthorizationHeader());

    URI localVarUri = URI.create(memberVarBaseUri + localVarPath);
    localVarRequestBuilder.uri(localVarUri);

    if (sharedSecret != null) {
      localVarRequestBuilder.header("Content-Type", "application/json");
    }
    localVarRequestBuilder.header("Accept", "application/json");
    localVarRequestBuilder.header("User-Agent", "ixopay-java-sdk 3.0.0");

    byte[] localVarSignatureBody = new byte[0];
    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }

    HttpRequestInfo localVarRequestInfo = ApiRequestSigner.requestInfo()
      .withUri(localVarUri)
      .withMethod("GET")
      .withContentTypeHeader("application/json")
      .withBody(localVarSignatureBody)
      .build();
    localVarRequestBuilder.header(HttpHeaders.date(), localVarRequestInfo.getNow());
    if(sharedSecret != null && localVarSignatureBody != null) {
      ApiRequestHeadersSignature signature = ApiRequestSigner.sign(sharedSecret, localVarRequestInfo);

      localVarRequestBuilder.header(HttpHeaders.xSignature(), signature.getXSignatureHeader());
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Pause a schedule. Requires the registrationId of an existing transaction of type Register / Debit-with-register / Preuathorize-with-register
   * 
   * @param apiKey API Key of Connector (required)
   * @param scheduleId ID of the schedule (required)
   * @param pauseSchedule Pause a schedule (required)
   * @return MaybeScheduleResponse
   * @throws ApiException if fails to make API call
   */
  public MaybeScheduleResponse pauseSchedule(String apiKey, String scheduleId, PauseSchedule pauseSchedule) throws ApiException {
    return  pauseSchedule(null, apiKey, scheduleId, pauseSchedule);
  }

  /**
   * Pause a schedule. Requires the registrationId of an existing transaction of type Register / Debit-with-register / Preuathorize-with-register
   * 
   * @param sharedSecret optional shared secret for signing requests (can be {@code null}).
   * @param apiKey API Key of Connector (required)
   * @param scheduleId ID of the schedule (required)
   * @param pauseSchedule Pause a schedule (required)
   * @return MaybeScheduleResponse
   * @throws ApiException if fails to make API call
   */
  public MaybeScheduleResponse pauseSchedule(@Nullable String sharedSecret, String apiKey, String scheduleId, PauseSchedule pauseSchedule) throws ApiException {
    ApiResponse<MaybeScheduleResponse> localVarResponse = pauseScheduleWithHttpInfo(sharedSecret, apiKey, scheduleId, pauseSchedule);
    return localVarResponse.getData();
  }

  /**
   * Pause a schedule. Requires the registrationId of an existing transaction of type Register / Debit-with-register / Preuathorize-with-register
   * 
   * @param apiKey API Key of Connector (required)
   * @param scheduleId ID of the schedule (required)
   * @param pauseSchedule Pause a schedule (required)
   * @return ApiResponse&lt;MaybeScheduleResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MaybeScheduleResponse> pauseScheduleWithHttpInfo(String apiKey, String scheduleId, PauseSchedule pauseSchedule) throws ApiException {
    return pauseScheduleWithHttpInfo(null, apiKey, scheduleId, pauseSchedule);
  }

  /**
   * Pause a schedule. Requires the registrationId of an existing transaction of type Register / Debit-with-register / Preuathorize-with-register
   * 
   * @param sharedSecret optional shared secret for signing requests (can be {@code null}).
   * @param apiKey API Key of Connector (required)
   * @param scheduleId ID of the schedule (required)
   * @param pauseSchedule Pause a schedule (required)
   * @return ApiResponse&lt;MaybeScheduleResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MaybeScheduleResponse> pauseScheduleWithHttpInfo(@Nullable String sharedSecret, String apiKey, String scheduleId, PauseSchedule pauseSchedule) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = pauseScheduleRequestBuilder(sharedSecret, apiKey, scheduleId, pauseSchedule);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        return new ApiResponse<MaybeScheduleResponse>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<MaybeScheduleResponse>() {}) // closes the InputStream
          
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder pauseScheduleRequestBuilder(@Nullable String sharedSecret, String apiKey, String scheduleId, PauseSchedule pauseSchedule) throws ApiException {
    // verify the required parameter 'apiKey' is set
    if (apiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'apiKey' when calling pauseSchedule");
    }
    // verify the required parameter 'scheduleId' is set
    if (scheduleId == null) {
      throw new ApiException(400, "Missing the required parameter 'scheduleId' when calling pauseSchedule");
    }
    // verify the required parameter 'pauseSchedule' is set
    if (pauseSchedule == null) {
      throw new ApiException(400, "Missing the required parameter 'pauseSchedule' when calling pauseSchedule");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/schedule/{apiKey}/{scheduleId}/pause"
        .replace("{apiKey}", ApiClient.urlEncode(apiKey.toString()))
        .replace("{scheduleId}", ApiClient.urlEncode(scheduleId.toString()));

    ApiRequestHeadersAuthentication authentication = ApiRequestAuthenticator.authenticate(memberVarApiUser);
    localVarRequestBuilder.header(HttpHeaders.authorization(), authentication.getAuthorizationHeader());

    URI localVarUri = URI.create(memberVarBaseUri + localVarPath);
    localVarRequestBuilder.uri(localVarUri);

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");
    localVarRequestBuilder.header("User-Agent", "ixopay-java-sdk 3.0.0");

    byte[] localVarSignatureBody;
    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(pauseSchedule);
      localVarSignatureBody = localVarPostBody;
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }

    HttpRequestInfo localVarRequestInfo = ApiRequestSigner.requestInfo()
      .withUri(localVarUri)
      .withMethod("POST")
      .withContentTypeHeader("application/json")
      .withBody(localVarSignatureBody)
      .build();
    localVarRequestBuilder.header(HttpHeaders.date(), localVarRequestInfo.getNow());
    if(sharedSecret != null && localVarSignatureBody != null) {
      ApiRequestHeadersSignature signature = ApiRequestSigner.sign(sharedSecret, localVarRequestInfo);

      localVarRequestBuilder.header(HttpHeaders.xSignature(), signature.getXSignatureHeader());
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Start a schedule. Requires the registrationId of an existing transaction of type Register / Debit-with-register / Preauthorize-with-register
   * 
   * @param apiKey API Key of Connector (required)
   * @param startSchedule Start a schedule on the given registration transaction (required)
   * @return MaybeScheduleResponse
   * @throws ApiException if fails to make API call
   */
  public MaybeScheduleResponse startSchedule(String apiKey, StartSchedule startSchedule) throws ApiException {
    return  startSchedule(null, apiKey, startSchedule);
  }

  /**
   * Start a schedule. Requires the registrationId of an existing transaction of type Register / Debit-with-register / Preauthorize-with-register
   * 
   * @param sharedSecret optional shared secret for signing requests (can be {@code null}).
   * @param apiKey API Key of Connector (required)
   * @param startSchedule Start a schedule on the given registration transaction (required)
   * @return MaybeScheduleResponse
   * @throws ApiException if fails to make API call
   */
  public MaybeScheduleResponse startSchedule(@Nullable String sharedSecret, String apiKey, StartSchedule startSchedule) throws ApiException {
    ApiResponse<MaybeScheduleResponse> localVarResponse = startScheduleWithHttpInfo(sharedSecret, apiKey, startSchedule);
    return localVarResponse.getData();
  }

  /**
   * Start a schedule. Requires the registrationId of an existing transaction of type Register / Debit-with-register / Preauthorize-with-register
   * 
   * @param apiKey API Key of Connector (required)
   * @param startSchedule Start a schedule on the given registration transaction (required)
   * @return ApiResponse&lt;MaybeScheduleResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MaybeScheduleResponse> startScheduleWithHttpInfo(String apiKey, StartSchedule startSchedule) throws ApiException {
    return startScheduleWithHttpInfo(null, apiKey, startSchedule);
  }

  /**
   * Start a schedule. Requires the registrationId of an existing transaction of type Register / Debit-with-register / Preauthorize-with-register
   * 
   * @param sharedSecret optional shared secret for signing requests (can be {@code null}).
   * @param apiKey API Key of Connector (required)
   * @param startSchedule Start a schedule on the given registration transaction (required)
   * @return ApiResponse&lt;MaybeScheduleResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MaybeScheduleResponse> startScheduleWithHttpInfo(@Nullable String sharedSecret, String apiKey, StartSchedule startSchedule) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = startScheduleRequestBuilder(sharedSecret, apiKey, startSchedule);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        return new ApiResponse<MaybeScheduleResponse>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<MaybeScheduleResponse>() {}) // closes the InputStream
          
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder startScheduleRequestBuilder(@Nullable String sharedSecret, String apiKey, StartSchedule startSchedule) throws ApiException {
    // verify the required parameter 'apiKey' is set
    if (apiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'apiKey' when calling startSchedule");
    }
    // verify the required parameter 'startSchedule' is set
    if (startSchedule == null) {
      throw new ApiException(400, "Missing the required parameter 'startSchedule' when calling startSchedule");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/schedule/{apiKey}/start"
        .replace("{apiKey}", ApiClient.urlEncode(apiKey.toString()));

    ApiRequestHeadersAuthentication authentication = ApiRequestAuthenticator.authenticate(memberVarApiUser);
    localVarRequestBuilder.header(HttpHeaders.authorization(), authentication.getAuthorizationHeader());

    URI localVarUri = URI.create(memberVarBaseUri + localVarPath);
    localVarRequestBuilder.uri(localVarUri);

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");
    localVarRequestBuilder.header("User-Agent", "ixopay-java-sdk 3.0.0");

    byte[] localVarSignatureBody;
    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(startSchedule);
      localVarSignatureBody = localVarPostBody;
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }

    HttpRequestInfo localVarRequestInfo = ApiRequestSigner.requestInfo()
      .withUri(localVarUri)
      .withMethod("POST")
      .withContentTypeHeader("application/json")
      .withBody(localVarSignatureBody)
      .build();
    localVarRequestBuilder.header(HttpHeaders.date(), localVarRequestInfo.getNow());
    if(sharedSecret != null && localVarSignatureBody != null) {
      ApiRequestHeadersSignature signature = ApiRequestSigner.sign(sharedSecret, localVarRequestInfo);

      localVarRequestBuilder.header(HttpHeaders.xSignature(), signature.getXSignatureHeader());
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Update a schedule. Requires the registrationId of an existing transaction of type Register / Debit-with-register / Preauthorize-with-register
   * 
   * @param apiKey API Key of Connector (required)
   * @param scheduleId ID of the schedule (required)
   * @param updateSchedule Update a schedule with given parameters (required)
   * @return MaybeScheduleResponse
   * @throws ApiException if fails to make API call
   */
  public MaybeScheduleResponse updateSchedule(String apiKey, String scheduleId, UpdateSchedule updateSchedule) throws ApiException {
    return  updateSchedule(null, apiKey, scheduleId, updateSchedule);
  }

  /**
   * Update a schedule. Requires the registrationId of an existing transaction of type Register / Debit-with-register / Preauthorize-with-register
   * 
   * @param sharedSecret optional shared secret for signing requests (can be {@code null}).
   * @param apiKey API Key of Connector (required)
   * @param scheduleId ID of the schedule (required)
   * @param updateSchedule Update a schedule with given parameters (required)
   * @return MaybeScheduleResponse
   * @throws ApiException if fails to make API call
   */
  public MaybeScheduleResponse updateSchedule(@Nullable String sharedSecret, String apiKey, String scheduleId, UpdateSchedule updateSchedule) throws ApiException {
    ApiResponse<MaybeScheduleResponse> localVarResponse = updateScheduleWithHttpInfo(sharedSecret, apiKey, scheduleId, updateSchedule);
    return localVarResponse.getData();
  }

  /**
   * Update a schedule. Requires the registrationId of an existing transaction of type Register / Debit-with-register / Preauthorize-with-register
   * 
   * @param apiKey API Key of Connector (required)
   * @param scheduleId ID of the schedule (required)
   * @param updateSchedule Update a schedule with given parameters (required)
   * @return ApiResponse&lt;MaybeScheduleResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MaybeScheduleResponse> updateScheduleWithHttpInfo(String apiKey, String scheduleId, UpdateSchedule updateSchedule) throws ApiException {
    return updateScheduleWithHttpInfo(null, apiKey, scheduleId, updateSchedule);
  }

  /**
   * Update a schedule. Requires the registrationId of an existing transaction of type Register / Debit-with-register / Preauthorize-with-register
   * 
   * @param sharedSecret optional shared secret for signing requests (can be {@code null}).
   * @param apiKey API Key of Connector (required)
   * @param scheduleId ID of the schedule (required)
   * @param updateSchedule Update a schedule with given parameters (required)
   * @return ApiResponse&lt;MaybeScheduleResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MaybeScheduleResponse> updateScheduleWithHttpInfo(@Nullable String sharedSecret, String apiKey, String scheduleId, UpdateSchedule updateSchedule) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updateScheduleRequestBuilder(sharedSecret, apiKey, scheduleId, updateSchedule);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        return new ApiResponse<MaybeScheduleResponse>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<MaybeScheduleResponse>() {}) // closes the InputStream
          
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updateScheduleRequestBuilder(@Nullable String sharedSecret, String apiKey, String scheduleId, UpdateSchedule updateSchedule) throws ApiException {
    // verify the required parameter 'apiKey' is set
    if (apiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'apiKey' when calling updateSchedule");
    }
    // verify the required parameter 'scheduleId' is set
    if (scheduleId == null) {
      throw new ApiException(400, "Missing the required parameter 'scheduleId' when calling updateSchedule");
    }
    // verify the required parameter 'updateSchedule' is set
    if (updateSchedule == null) {
      throw new ApiException(400, "Missing the required parameter 'updateSchedule' when calling updateSchedule");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/schedule/{apiKey}/{scheduleId}/update"
        .replace("{apiKey}", ApiClient.urlEncode(apiKey.toString()))
        .replace("{scheduleId}", ApiClient.urlEncode(scheduleId.toString()));

    ApiRequestHeadersAuthentication authentication = ApiRequestAuthenticator.authenticate(memberVarApiUser);
    localVarRequestBuilder.header(HttpHeaders.authorization(), authentication.getAuthorizationHeader());

    URI localVarUri = URI.create(memberVarBaseUri + localVarPath);
    localVarRequestBuilder.uri(localVarUri);

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");
    localVarRequestBuilder.header("User-Agent", "ixopay-java-sdk 3.0.0");

    byte[] localVarSignatureBody;
    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(updateSchedule);
      localVarSignatureBody = localVarPostBody;
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }

    HttpRequestInfo localVarRequestInfo = ApiRequestSigner.requestInfo()
      .withUri(localVarUri)
      .withMethod("POST")
      .withContentTypeHeader("application/json")
      .withBody(localVarSignatureBody)
      .build();
    localVarRequestBuilder.header(HttpHeaders.date(), localVarRequestInfo.getNow());
    if(sharedSecret != null && localVarSignatureBody != null) {
      ApiRequestHeadersSignature signature = ApiRequestSigner.sign(sharedSecret, localVarRequestInfo);

      localVarRequestBuilder.header(HttpHeaders.xSignature(), signature.getXSignatureHeader());
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
}
